import { ReactQueryClientProvider } from '@/providers/react-query'
import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"
import { NextAuthProvider } from '@/providers/next-auth'
import { Navbar } from './_components/app/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Platform',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <ReactQueryClientProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className}>
          <NextAuthProvider>
            <Navbar />
            {children}
            <Toaster />
          </NextAuthProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}
